name: studyflix
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Ensure the Dart version is correctly specified

dependencies:
  flutter:
    sdk: flutter

  # iOS style icons
  cupertino_icons: ^1.0.8

  # Smooth page indicators
  smooth_page_indicator: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting rules for Flutter
  flutter_lints: ^4.0.0

flutter:
  # Use material design icons
  uses-material-design: true

  # Add image assets
  assets:
    - assets/images/
  # Add custom fonts
  fonts:
    - family: "OpenSans Bold"
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
    - family: "OpenSans Medium"
      fonts:
        - asset: assets/fonts/OpenSans-Medium.ttf
    - family: "OpenSans Regular"
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
