name: studyflix
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Ensure the Dart version is correctly specified

dependencies:
  flutter:
    sdk: flutter

  # iOS style icons
  cupertino_icons: ^1.0.8

  # Smooth page indicators
  smooth_page_indicator: ^1.0.0
  carousel_slider: ^5.0.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  equatable: ^2.0.7
  uuid: ^4.5.1
  dartz: ^0.10.1
  flutter_bloc: ^9.0.0
  image_picker: ^1.1.2
  provider: ^6.1.2
  get_it: ^8.0.3
  shared_preferences: ^2.5.1
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  json_annotation: ^4.9.0
  permission_handler: ^11.4.0
  fluttertoast: ^8.2.12
  flutter_svg: ^2.0.17
  video_player: ^2.9.3
  sensors_plus: ^6.1.1
  connectivity_plus: ^6.1.3
  mocktail: ^1.0.4
  test_cov_console: ^0.2.2
  flutter_test:
    sdk: flutter

dev_dependencies:

  # Linting rules for Flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.14
  hive_generator: ^2.0.1
  json_serializable: ^6.9.0

flutter:
  # Use material design icons
  uses-material-design: true

  # Add image assets
  assets:
    - assets/images/

  # Add custom fonts
  fonts:
    - family: "OpenSans Bold"
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
    - family: "OpenSans Medium"
      fonts:
        - asset: assets/fonts/OpenSans-Medium.ttf
    - family: "OpenSans Regular"
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf